name: Java CI Deploy

on:
 workflow_dispatch:
   inputs:
     environment:
       description: 'Env to deploy'
       required: true
       default: 'dev'
       type: choice
       options:
         - dev
         - test
         - prod
     jiraIssue:
      default: ''
      description: 'Jira issue number'
      required: false

permissions:
  contents: write

jobs:
  merge-pr:
    name: Merge PR
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        run: actions/checkout@v6

      - name: Merge pr
        run: gh pr merge --auto -squash "$PR_URL"
        env:
          PR_URL: ${{ github.envent.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV: ${{ inputs.environment }}

  deploy:
    name: Merge PR
    needs: merge-pr
    runs-on: ubuntu-latest
    steps:
      - name: Deploy.git
        uses: ./.github/workflows/app-build.yml@main

      - name: create Tag
        id: logging
        if: contains(env.environment, 'dev') && success()
        run: |
          echo "$(date)"
